### PR TITLE
Clean-up + Bug fix for the loop nodes

### LINKED ISSUE #90: Clean-up Loops
I think loops should receive a little clean-up.

For now, there are 3 loop nodes in the add menu. But actually, only one of them is really required: **The loop caller**. Since the other nodes you need for a loop (**object loop** and **generic loop**) can be created directly from the **loop caller** node by pressing **New Loop**.

I think it would make more sense to rename *"loop caller"* to just *"loop"* in the add menu and remove **object loop** and **generic loop** from the add menu. 

I think this could decrease confusion for new users and make the add menu a little less crowded :wink: 

----------

PS: Since I heard you were not going to actively develop this add-on anymore. I am willing to look into this if you want.

### PR DESCRIPTION
**Pull request by azerupi**
Fixes #90 

This pull request contains commits that:

- clean up the add menu to have 1 loop node (previously *loop caller*)
- automatically change the sockets of the loop caller in function of the selected loop
- prevent the selected loop from changing when a new loop is added

I propose you test this before you accept it so that I don't introduce bugs in master :)

### CODE REVIEW

**Comment by azerupi** [comment]
There is still a bug:
When you add a new loop caller via a loop node with that + icon. The activeLoop = the loop you created it with. But the dropdown shows another loop...

**Comment by JacquesLucke** [comment]
I currently have a small wlan problem what makes some things more difficult. 
It looks like you accidently changed all tabs to whitespaces.. that makes it very hard to see the differences in your commits. Can you maybe convert them back to tabs?

**Comment by azerupi** [comment]
Yes sorry for that. But my editor was drawing warnings everywhere because PEP8 says the way to indent python code is with spaces https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces So I let my editor convert everything so that he would be happy. 

The changes:

**First Commit**
```python
   nodes.append(("System", [
       ("mn_LoopCallerNode", "Loop Caller"),
       ("mn_LoopStartNode", "Generic Loop", {"preset" : repr("NONE")}),
       ("mn_LoopStartNode", "Object Loop", {"preset" : repr("OBJECT")}),
```
to
```python
   nodes.append(("System", [
        ("mn_LoopCallerNode", "Loop"),
```

**Second Commit**
```python
selectedLoop = bpy.props.EnumProperty(items = getStartLoopNodeItems, name = "Selected Loop")
```
to
```python
def updateActiveL(self, context):
        self.updateActiveLoop()

selectedLoop = bpy.props.EnumProperty(
        items=getStartLoopNodeItems,
        name="Selected Loop",
        update=updateActiveL)
```

**Third Commit**

No problem with that one it's readable :)

**Comment by azerupi** [comment]
I managed to fix the bug I mentioned earlier :)

**Comment by azerupi** [comment]
I think I finally got it to work the way I want :) I don't see any bugs in the loop nodes anymore

**Comment by azerupi** [comment]
@JacquesLucke Have you had a chance to test it yet?

**Comment by JacquesLucke** [comment]
No sorry, no chance yet. I will let you know!

**Comment by JacquesLucke** [comment]
I will check it now. I'm sorry but before I can merge it you have to try to replace the whitespaces with tabs again.. :/ for consistency reasons. Or you say that I should do it after the merge...

thanks for you work btw :)

**Comment by JacquesLucke** [comment]
And you should remove the code you commented out.

Sometimes I still get an weird behavior. I select a loop name from the drop down menu. the Active loop changes to the one I clicked, but the enum property still shows another name. do you have this too?

**Comment by azerupi** [comment]
Ok, well what I'm going to do is delete this pull request. Start from your latest commit and just make the changes I did. It will be cleaner that way. As for the odd behaviour, I will check. Can you maybe point out after what manipulation that happened?

**Comment by JacquesLucke** [comment]
sure, just add a loop call node and two object loops. then switch the name in the drop down menu for multiple times.. sometimes I get the described behavior

**Pull request closed without merging**
